[project]
name = "process-template"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "automation-server-client",
    "kmd-nexus-client",
    "odk-tools",
    "rapidfuzz>=3.14.5",
    "ruff>=0.15.12",
    "sbsys",
    "xflow-client",
]

[tool.uv.sources]
automation-server-client = { git = "https://github.com/odense-rpa/automation-server-client.git", tag = "v0.3.0" }
odk-tools = { git = "https://github.com/odense-rpa/odk-tools.git" }
xflow-client = { git = "https://github.com/odense-rpa/xflow-client.git" }
kmd-nexus-client = { git = "https://github.com/odense-rpa/nexus-client.git" }
sbsys = { git = "https://github.com/odense-rpa/sbsys-ng.git" }
